### ISSUE TITLE
Call to a member function getLayout() on null

### ISSUE THREAD

**Issue by fiedsch** [contao-bootstrap/layout#10]
After upgrading to 2.0.2 I get the above error. It looks like the `onParseTemplate()` never gets called resulting in `$template->bootstrapEnvironment` not being set.

After a downgrade to 2.0.1 all is well again. This was reproduceable in several installations.

**Comment by dmolineus** [comment]
Should be fixed with d9b218689254342d5a75acd5e990a6df7cbe8466. The hook listener was registered by a tagged which is not supported in Contao 4.4. Would be great if you can confirm that branch hotfix/2.0.3 works now.

**Comment by fiedsch** [comment]
Works, thank you!

**Comment by dmolineus** [comment]
Released as 2.0.3
