### ISSUE TITLE
Conflict with contao_dk_mmenu

### ISSUE THREAD

**Issue by cmichael-de** [contao-bootstrap/layout#12]
Hi David, I found a conflict between contao_dk_mmenu and contao-bootstrap/layout. I guess bootstrap/layout/blob/master/src/Resources/config/contao_bootstrap.yml replaces the css "invisible" with css class "sr-only". The contao_dk_mmenu does not work correctly with "sr-only" and the mmenu stays hidden (https://github.com/FrDH/mmenu-js/issues/1041). My workaround for now is to create a custom template mod_mmenu.html5 where I go to remove the "invisible". Not sure if there is a better way.

**Comment by cmichael-de** [comment]
I also created an issue on https://github.com/dklemmt/contao_dk_mmenu/issues/38.

**Comment by dmolineus** [comment]
Yes the invisible classes are replaced. They are replaced in the parsed fe_* template. You could try to include the dk_mmenu using an html module with an insert tag `{{insert_module::id-of-mm-menu}}`. The insert tags are replaced after the classes are replaced so that might work.

**Comment by cmichael-de** [comment]
Works like a charm! 
And is a better solution, cause my solution (removement of "invisible") makes the dk_mmenu occure shortly while page is loading.
