### ISSUE TITLE
Conflict with contao-lazy-images and "img-fluid" class

### ISSUE THREAD

**Issue by cmichael-de** [contao-bootstrap/layout#15]
Read more here: https://github.com/derhaeuptling/contao-lazy-images/issues/11

**Comment by cmichael-de** [comment]
I suggest to add known conflicts to contao-bootstrap/composer.json.
Would be helpful for all contao-bootstrap useres (for you as well ;-).

https://github.com/derhaeuptling/contao-lazy-images/issues/11

**Comment by dmolineus** [comment]
Instead of defining an conflict the issue schould be solved.

Contao bootstrap renders a `class` attribute using the `$this->attributes` of the template because the previous Contao core picture template didn't have the class attribute computed in the template.

**Comment by dmolineus** [comment]
Behoben mit Release 2.0.4.
