### ISSUE TITLE
Typed property ContaoBootstrap\Layout\Helper\LayoutHelper::$mainClass must not be accessed before initialization

### ISSUE THREAD

**Issue by srhinow** [contao-bootstrap/layout#23]
in Contao 4.13.13 und der dev-master Version von Alex kommt ein Fehler wenn man (bei mir leicht modifiziert aber sonst genau das selbe wie die fe_bootstrap.html5. Lief aber vorher unter Contao 4.9). 

![grafik](https://user-images.githubusercontent.com/741418/202682503-ec0fd76a-3399-4160-9569-a13711d78d25.png)

StackTrace:
`Error:
Typed property ContaoBootstrap\Layout\Helper\LayoutHelper::$mainClass must not be accessed before initialization

  at vendor/contao-bootstrap/layout/src/Helper/LayoutHelper.php:147
  at ContaoBootstrap\Layout\Helper\LayoutHelper->getAttributes()
     (templates/zfib/fe_zfib_right_col.html5:55)
  at include('/var/www/z/ZfiB/contao/templates/zfib/fe_zfib_right_col.html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:108)
  at Contao\Template->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:295)
  at Contao\Template->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:43)
  at Contao\FrontendTemplate->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:116)
  at Contao\FrontendTemplate->compile()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Template.php:322)
  at Contao\Template->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/FrontendTemplate.php:85)
  at Contao\FrontendTemplate->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:62)
  at Contao\PageRegular->getResponse()
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:320)
  at Contao\FrontendIndex->renderPage()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:75)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)
  at require('/var/www/z/ZfiB/contao/web/index.php')
     (web/app.php:13) `

Das gleiche kommt auch mit <?= $helper->getAttributes($helper::LEFT) ?> oder <?= $helper->getAttributes($helper::RIGHT) ?>

Da ich bei Alex kein Issue aufmachen kann, schreibe ich es hier.

**Comment by dmolineus** [comment]
Der Branch von Alex hat keine vollständige PHP 8 Unterstützung. Der Fehler tritt nicht mit c4cd46752f62772ebf3f8f650f04f26f6c383ce1 auf.
