### ISSUE TITLE
Duplicate ID

### ISSUE THREAD

**Issue by tristanlins** [contao-bootstrap/layout#3]
The ID output [here](https://github.com/contao-bootstrap/layout/blob/master/module/templates/3.2/block_section.html5#L2) result in duplicate ID, because contao 3.4 already wrap the elements in the custom block section within a `<div id="<?php echo $customElementId; ?>">` element.

**Comment by dmolineus** [comment]
Fixed in 736662f1811dbdc95d69698a30e55e98f3897004.
