### ISSUE TITLE
Error bootstrap/layout v2.0.0  | Contao 4.5.1

### ISSUE THREAD

**Issue by chriza** [contao-bootstrap/layout#8]
Nach Installieren von bootstrap/layout v2.0.0 erscheint beim Klicken auf das Seitenlayout-Symbol folgender Fehler:

Internal Server Error
Was ist das Problem?

Attempted to call an undefined method named "generateSubSelectPalettes" of class "ContaoCommunityAlliance\MetaPalettes\Listener\SubSelectPalettesListener".

**Comment by dmolineus** [comment]
Will be fixed with https://github.com/contao-community-alliance/meta-palettes/pull/38

**Comment by dmolineus** [comment]
Bug is fixed in contao-community-alliance/meta-palettes. An composer update should fix the issue.
